obstacles:
- angular_speed: 0.0
  is_dynamic: false
  name: VerticalWall_Ball_0_0
  position:
  - 0.2899999999999999
  - -0.15
  - 0.08
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.0
  is_dynamic: false
  name: VerticalWall_Ball_0_1
  position:
  - 0.2899999999999999
  - -0.15
  - 0.16
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.0
  is_dynamic: false
  name: VerticalWall_Ball_0_2
  position:
  - 0.2899999999999999
  - -0.15
  - 0.24
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.0
  is_dynamic: false
  name: VerticalWall_Ball_0_3
  position:
  - 0.2899999999999999
  - -0.15
  - 0.32
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.0
  is_dynamic: false
  name: VerticalWall_Ball_0_4
  position:
  - 0.2899999999999999
  - -0.15
  - 0.4
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.0
  is_dynamic: false
  name: VerticalWall_Ball_0_5
  position:
  - 0.2899999999999999
  - -0.15
  - 0.48000000000000004
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.0
  is_dynamic: false
  name: VerticalWall_Ball_0_6
  position:
  - 0.2899999999999999
  - -0.15
  - 0.5599999999999999
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.0
  is_dynamic: false
  name: TopWall_Ball_0_0
  position:
  - 0.44999999999999996
  - -0.15
  - 0.64
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.0
  is_dynamic: false
  name: TopWall_Ball_0_1
  position:
  - 0.36999999999999994
  - -0.15
  - 0.64
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.0
  is_dynamic: false
  name: TopWall_Ball_0_2
  position:
  - 0.2899999999999999
  - -0.15
  - 0.64
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.0
  is_dynamic: false
  name: TopWall_Ball_0_3
  position:
  - 0.20999999999999996
  - -0.15
  - 0.64
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.0
  is_dynamic: false
  name: TopWall_Ball_0_4
  position:
  - 0.12999999999999995
  - -0.15
  - 0.64
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.0
  is_dynamic: false
  name: BottomWall_Ball_0_0
  position:
  - 0.44999999999999996
  - -0.15
  - 0
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.0
  is_dynamic: false
  name: BottomWall_Ball_0_1
  position:
  - 0.36999999999999994
  - -0.15
  - 0
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.0
  is_dynamic: false
  name: BottomWall_Ball_0_2
  position:
  - 0.2899999999999999
  - -0.15
  - 0
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.0
  is_dynamic: false
  name: BottomWall_Ball_0_3
  position:
  - 0.20999999999999996
  - -0.15
  - 0
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.0
  is_dynamic: false
  name: BottomWall_Ball_0_4
  position:
  - 0.12999999999999995
  - -0.15
  - 0
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
