obstacles:
- angular_speed: 0.1
  is_dynamic: false
  name: VerticalWall_Ball_0_0
  position:
  - 1.0
  - 0
  - 0.08
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: VerticalWall_Ball_0_1
  position:
  - 1.0
  - 0
  - 0.16
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: VerticalWall_Ball_0_2
  position:
  - 1.0
  - 0
  - 0.24
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: VerticalWall_Ball_0_3
  position:
  - 1.0
  - 0
  - 0.32
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: VerticalWall_Ball_0_4
  position:
  - 1.0
  - 0
  - 0.4
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: VerticalWall_Ball_0_5
  position:
  - 1.0
  - 0
  - 0.48000000000000004
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: VerticalWall_Ball_0_6
  position:
  - 1.0
  - 0
  - 0.5599999999999999
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: VerticalWall_Ball_1_0
  position:
  - 0.92
  - 0
  - 0.08
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: VerticalWall_Ball_1_1
  position:
  - 0.92
  - 0
  - 0.16
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: VerticalWall_Ball_1_2
  position:
  - 0.92
  - 0
  - 0.24
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: VerticalWall_Ball_1_3
  position:
  - 0.92
  - 0
  - 0.32
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: VerticalWall_Ball_1_4
  position:
  - 0.92
  - 0
  - 0.4
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: VerticalWall_Ball_1_5
  position:
  - 0.92
  - 0
  - 0.48000000000000004
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: VerticalWall_Ball_1_6
  position:
  - 0.92
  - 0
  - 0.5599999999999999
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: VerticalWall_Ball_2_0
  position:
  - 0.84
  - 0
  - 0.08
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: VerticalWall_Ball_2_1
  position:
  - 0.84
  - 0
  - 0.16
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: VerticalWall_Ball_2_2
  position:
  - 0.84
  - 0
  - 0.24
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: VerticalWall_Ball_2_3
  position:
  - 0.84
  - 0
  - 0.32
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: VerticalWall_Ball_2_4
  position:
  - 0.84
  - 0
  - 0.4
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: VerticalWall_Ball_2_5
  position:
  - 0.84
  - 0
  - 0.48000000000000004
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: VerticalWall_Ball_2_6
  position:
  - 0.84
  - 0
  - 0.5599999999999999
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: VerticalWall_Ball_3_0
  position:
  - 0.76
  - 0
  - 0.08
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: VerticalWall_Ball_3_1
  position:
  - 0.76
  - 0
  - 0.16
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: VerticalWall_Ball_3_2
  position:
  - 0.76
  - 0
  - 0.24
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: VerticalWall_Ball_3_3
  position:
  - 0.76
  - 0
  - 0.32
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: VerticalWall_Ball_3_4
  position:
  - 0.76
  - 0
  - 0.4
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: VerticalWall_Ball_3_5
  position:
  - 0.76
  - 0
  - 0.48000000000000004
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: VerticalWall_Ball_3_6
  position:
  - 0.76
  - 0
  - 0.5599999999999999
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: VerticalWall_Ball_4_0
  position:
  - 0.6799999999999999
  - 0
  - 0.08
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: VerticalWall_Ball_4_1
  position:
  - 0.6799999999999999
  - 0
  - 0.16
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: VerticalWall_Ball_4_2
  position:
  - 0.6799999999999999
  - 0
  - 0.24
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: VerticalWall_Ball_4_3
  position:
  - 0.6799999999999999
  - 0
  - 0.32
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: VerticalWall_Ball_4_4
  position:
  - 0.6799999999999999
  - 0
  - 0.4
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: VerticalWall_Ball_4_5
  position:
  - 0.6799999999999999
  - 0
  - 0.48000000000000004
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: VerticalWall_Ball_4_6
  position:
  - 0.6799999999999999
  - 0
  - 0.5599999999999999
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: TopWall_Ball_0_0
  position:
  - 1.0
  - -0.12
  - 0.64
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: TopWall_Ball_0_1
  position:
  - 0.92
  - -0.12
  - 0.64
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: TopWall_Ball_0_2
  position:
  - 0.84
  - -0.12
  - 0.64
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: TopWall_Ball_0_3
  position:
  - 0.76
  - -0.12
  - 0.64
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: TopWall_Ball_0_4
  position:
  - 0.6799999999999999
  - -0.12
  - 0.64
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: TopWall_Ball_1_0
  position:
  - 1.0
  - -0.039999999999999994
  - 0.64
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: TopWall_Ball_1_1
  position:
  - 0.92
  - -0.039999999999999994
  - 0.64
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: TopWall_Ball_1_2
  position:
  - 0.84
  - -0.039999999999999994
  - 0.64
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: TopWall_Ball_1_3
  position:
  - 0.76
  - -0.039999999999999994
  - 0.64
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: TopWall_Ball_1_4
  position:
  - 0.6799999999999999
  - -0.039999999999999994
  - 0.64
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: TopWall_Ball_2_0
  position:
  - 1.0
  - 0.04000000000000001
  - 0.64
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: TopWall_Ball_2_1
  position:
  - 0.92
  - 0.04000000000000001
  - 0.64
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: TopWall_Ball_2_2
  position:
  - 0.84
  - 0.04000000000000001
  - 0.64
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: TopWall_Ball_2_3
  position:
  - 0.76
  - 0.04000000000000001
  - 0.64
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: TopWall_Ball_2_4
  position:
  - 0.6799999999999999
  - 0.04000000000000001
  - 0.64
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: TopWall_Ball_3_0
  position:
  - 1.0
  - 0.12
  - 0.64
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: TopWall_Ball_3_1
  position:
  - 0.92
  - 0.12
  - 0.64
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: TopWall_Ball_3_2
  position:
  - 0.84
  - 0.12
  - 0.64
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: TopWall_Ball_3_3
  position:
  - 0.76
  - 0.12
  - 0.64
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: TopWall_Ball_3_4
  position:
  - 0.6799999999999999
  - 0.12
  - 0.64
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: BottomWall_Ball_0_0
  position:
  - 1.0
  - -0.12
  - 0
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: BottomWall_Ball_0_1
  position:
  - 0.92
  - -0.12
  - 0
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: BottomWall_Ball_0_2
  position:
  - 0.84
  - -0.12
  - 0
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: BottomWall_Ball_0_3
  position:
  - 0.76
  - -0.12
  - 0
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: BottomWall_Ball_0_4
  position:
  - 0.6799999999999999
  - -0.12
  - 0
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: BottomWall_Ball_1_0
  position:
  - 1.0
  - -0.039999999999999994
  - 0
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: BottomWall_Ball_1_1
  position:
  - 0.92
  - -0.039999999999999994
  - 0
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: BottomWall_Ball_1_2
  position:
  - 0.84
  - -0.039999999999999994
  - 0
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: BottomWall_Ball_1_3
  position:
  - 0.76
  - -0.039999999999999994
  - 0
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: BottomWall_Ball_1_4
  position:
  - 0.6799999999999999
  - -0.039999999999999994
  - 0
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: BottomWall_Ball_2_0
  position:
  - 1.0
  - 0.04000000000000001
  - 0
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: BottomWall_Ball_2_1
  position:
  - 0.92
  - 0.04000000000000001
  - 0
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: BottomWall_Ball_2_2
  position:
  - 0.84
  - 0.04000000000000001
  - 0
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: BottomWall_Ball_2_3
  position:
  - 0.76
  - 0.04000000000000001
  - 0
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: BottomWall_Ball_2_4
  position:
  - 0.6799999999999999
  - 0.04000000000000001
  - 0
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: BottomWall_Ball_3_0
  position:
  - 1.0
  - 0.12
  - 0
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: BottomWall_Ball_3_1
  position:
  - 0.92
  - 0.12
  - 0
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: BottomWall_Ball_3_2
  position:
  - 0.84
  - 0.12
  - 0
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: BottomWall_Ball_3_3
  position:
  - 0.76
  - 0.12
  - 0
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
- angular_speed: 0.1
  is_dynamic: false
  name: BottomWall_Ball_3_4
  position:
  - 0.6799999999999999
  - 0.12
  - 0
  radius: 0.04
  velocity:
  - 0.0
  - 0.0
  - 0.0
